# Generated by Django 5.2.6 on 2025-09-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('initials', models.CharField(max_length=255)),
                ('city_of_birth', models.CharField(max_length=255)),
                ('country_of_birth', models.CharField(max_length=255)),
                ('country_of_representation', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('human', models.BooleanField(default=True)),
                ('profile_image', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'drivers',
                'indexes': [models.Index(fields=['last_name', 'first_name'], name='drivers_last_na_6d0279_idx')],
            },
        ),
    ]
