# Generated by Django 5.2.6 on 2026-08-27 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverRivalry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('content', models.TextField()),
                ('shared_races', models.PositiveIntegerField()),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('driver_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rivalries_as_a', to='drivers.driver')),
                ('driver_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rivalries_as_b', to='drivers.driver')),
            ],
            options={
                'verbose_name_plural': 'driver rivalries',
                'db_table': 'driver_rivalries',
                'constraints': [models.UniqueConstraint(fields=('driver_a', 'driver_b'), name='unique_driver_rivalry'), models.CheckConstraint(condition=models.Q(('driver_a__lt', models.F('driver_b'))), name='driver_rivalry_canonical_order')],
            },
        ),
    ]
