# Generated by Django 5.2.10 on 2026-03-11 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0002_raceresult_cleanest_driver_raceresult_most_overtakes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RECAP', 'Race Recap'), ('PREVIEW', 'Race Preview')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('teaser', models.TextField()),
                ('content', models.TextField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='results.race')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
