# Generated by Django 5.2.10 on 2026-03-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rivalry_callout',
            field=models.TextField(blank=True, default=''),
        ),
    ]
