# Generated by Django 5.2.10 on 2026-03-11 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_rivalry_callout'),
        ('results', '0002_raceresult_cleanest_driver_raceresult_most_overtakes'),
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='seasons.season'),
        ),
        migrations.AlterField(
            model_name='article',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='results.race'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('RECAP', 'Race Recap'), ('PREVIEW', 'Race Preview'), ('SEASON_RECAP', 'Season Recap'), ('SEASON_PREVIEW', 'Season Preview')], max_length=15),
        ),
    ]
