# Generated by Django 5.2.10 on 2026-03-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_season_article_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_sidebar',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
