# Generated by Django 5.2.6 on 2026-08-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_power_rankings'),
        ('results', '0005_add_quote_to_history_blurb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='session_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='session_races',
            field=models.ManyToManyField(blank=True, related_name='session_articles', to='results.race'),
        ),
        migrations.AlterField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('RECAP', 'Race Recap'), ('PREVIEW', 'Race Preview'), ('SEASON_RECAP', 'Season Recap'), ('SEASON_PREVIEW', 'Season Preview'), ('POWER_RANKINGS', 'Power Rankings'), ('SESSION', 'Session Report')], max_length=15),
        ),
    ]
