# Generated by Django 5.2.6 on 2026-08-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
        ('results', '0005_add_quote_to_history_blurb'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='issue',
            name='uniq_sent_issue_per_race',
        ),
        migrations.AddField(
            model_name='issue',
            name='kind',
            field=models.CharField(choices=[('RECAP', 'Race recap'), ('PREVIEW', 'Race preview')], default='RECAP', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(condition=models.Q(('sent_at__isnull', False)), fields=('race', 'kind'), name='uniq_sent_issue_per_race_kind'),
        ),
    ]
