# Generated by Django 5.2.6 on 2026-08-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_remove_issue_uniq_sent_issue_per_race_issue_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='kind',
            field=models.CharField(choices=[('RECAP', 'Race recap'), ('PREVIEW', 'Race preview'), ('SESSION', 'Session summary')], default='RECAP', max_length=10),
        ),
    ]
