# Generated by Django 5.2.6 on 2025-09-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'seasons',
                'ordering': ['id'],
            },
        ),
    ]
