# Generated by Django 5.2.10 on 2026-03-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='season_notes',
            field=models.TextField(blank=True, default='', help_text='Optional notes injected into season article prompts — e.g. major storylines, rule changes, driver transfers, or anything the AI should know about this season.'),
        ),
    ]
