# Generated by Django 5.2.6 on 2025-09-07 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
                ('distance', models.PositiveIntegerField(help_text='Track length in meters')),
                ('layout', models.CharField(blank=True, max_length=64)),
                ('img', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'tracks',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['country', 'name'], name='tracks_country_c99026_idx')],
            },
        ),
    ]
