# Generated by Django 5.2.10 on 2026-03-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='category',
            field=models.CharField(blank=True, choices=[('STREET', 'Street Circuit'), ('PERMANENT', 'Permanent Circuit')], default='', help_text='Street or permanent circuit classification', max_length=16),
        ),
    ]
