# Generated by Django 5.2.6 on 2025-09-07 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drivers', '0001_initial'),
        ('seasons', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_entries', to='seasons.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_entries', to='teams.team')),
            ],
            options={
                'db_table': 'team_seasons',
                'ordering': ['season_id', 'team_id'],
                'unique_together': {('season', 'team')},
            },
        ),
        migrations.CreateModel(
            name='DriverSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_reserve', models.BooleanField(default=False)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_entries', to='drivers.driver')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_entries', to='seasons.season')),
                ('team_season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='driver_seats', to='entries.teamseason')),
            ],
            options={
                'db_table': 'driver_seasons',
                'ordering': ['season_id', 'driver_id'],
                'unique_together': {('season', 'driver')},
            },
        ),
    ]
