# Generated by Django 5.2.6 on 2026-08-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driverrivalry'),
        ('entries', '0002_teamseason_color'),
        ('seasons', '0002_add_season_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driverseason',
            unique_together={('season', 'driver', 'team_season')},
        ),
    ]
