# Generated by Django 5.2.6 on 2025-09-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255, unique=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('founded', models.IntegerField(blank=True, null=True)),
                ('team_img', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['team_name'],
            },
        ),
    ]
